<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Data\Accidentes\2024-accidentes-trafico-detalle.csv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\Accidentes\2025-accidentes-trafico-detalle-csv.csv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\Accidentes\2026-accidentes-trafico-detalle-csv.csv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\Analyzers\" />
      <Folder Include="Services\File\Csv\" />
      <Folder Include="Storages\Files\" />
    </ItemGroup>

</Project>
